### ISSUE TITLE
レベル別達成度の可良評価数が正しくない

### ISSUE THREAD

**Issue by mel225** [Slime-hatena/ProjectPrimera#53]
### 現象

ユーザページ内のレベル別達成度内、可良...の評価の数値が正しくない。
具体的には、１／０ でしか表示されてない。

### 発生日時

2019/02/15 13:45頃

### ユーザーID

[238](https://ongeki-score.net/user/238)

### 再現方法

ユーザページにアクセスする。
おそらくすべてのアクセス可能なユーザページで発生している。

### OSバージョン

Windows 10 64-bit

### ブラウザ

Google Chrome
バージョン: 72.0.3626.96（Official Build） （64 ビット）

### その他

画像はユーザページ内のものです。html2canvasでレンダリングさせていただきました。

![bug_report1](https://user-images.githubusercontent.com/39999551/52835248-0a6f5780-3129-11e9-8a08-8316e7783b0d.png)

### メッセージ

お疲れ様です。
素晴らしいシステムをありがとうございます。
協力できるところはさせていただきたいので、よろしくお願いいたします。

**Comment by Slime-hatena** [comment]
ご報告ありがとうございます。
修正致しました。後ほどサイト側に修正を適用いたします。
