### ISSUE TITLE
リーセント候補曲にLuna楽曲が含まれている

### ISSUE THREAD

**Issue by Slime-hatena** [Slime-hatena/ProjectPrimera#90]
そもそもオンゲキの仕様上入らないので大嘘表示してる
実装時入らないことをすっかり忘れてました

一つ判定噛ませれば除外できそうだしそこまで難しくはなさそう

https://twitter.com/fumilin/status/1137301135482482688?s=20

**Comment by ethfumi** [comment]
修正確認できましたー。対応ありがとうございます！

**Comment by Slime-hatena** [comment]
@ethfumi 修正までかなり時間頂いてしまい申し訳ないです… ご報告ありがとうございました！
